# permissions for end users to edit medusabackupjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: medusabackupjob-editor-role
rules:
- apiGroups:
  - medusa.k8ssandra.io
  resources:
  - medusabackupjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - medusa.k8ssandra.io
  resources:
  - medusabackupjobs/status
  verbs:
  - get
