# permissions for end users to edit medusarestorejobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: medusarestorejob-editor-role
rules:
- apiGroups:
  - medusa.k8ssandra.io
  resources:
  - medusarestorejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - medusa.k8ssandra.io
  resources:
  - medusarestorejobs/status
  verbs:
  - get
