# permissions for end users to view medusarestorejobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: medusarestorejob-viewer-role
rules:
- apiGroups:
  - medusa.k8ssandra.io
  resources:
  - medusarestorejobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - medusa.k8ssandra.io
  resources:
  - medusarestorejobs/status
  verbs:
  - get
